spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: system
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
    continue-on-error: true
    hikari:
      connection-timeout: 20000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    com.xkcoding: debug
    com.xkcoding.orm.mybatis.MapperAndPage.mapper: trace
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.group4.backend.entity
